```{r include=FALSE}
opts_chunk$set(echo=FALSE)
opts_chunk$set(warning=FALSE)
opts_chunk$set(fig.pos = 'H')

library(MotifBinner2)

if (!exists('result'))
{
  result <- all_results[[grep('prepConfig', names(all_results))[1]]]
}
if (class(result) != 'prepConfig')
{
  result <- all_results[[grep('prepConfig', names(all_results))[1]]]
}
```
# Configuration and Timing

The configuration that was used in this run.

```{r, results='asis'}
cat("\n\nTable: General Settings\n\n")
print(format_table(result$metrics$other_settings))
```

```{r, results='asis'}
cat("\n\nTable: The operation specific settings\n\n")
print(format_table(result$metrics$flat_op_list))
```

NOTES:

```{r, results='asis'}
for (i in 1:nrow(result$metrics$input_files)){
  cat(paste("Operation number ", result$metrics$input_files[i,'op_num'], 
            " was a loadData operation from input file ", 
            result$metrics$input_files[i,'value'], 
            '\n\n', sep = ''))
}
```

The time it took to run the various steps

```{r, results='asis'}
print(timingTable(all_results))
```


```{r, results='asis'}
cat('\n\n---\n\n')
```
