### primerSeqErr report for `r data_source_name`

```{r, include=F}
fig.cap1 <- 'Substitution error rate by quality score'
let_to_int <- function(x){
  if (x == 'A') return(1)
  if (x == 'C') return(2)
  if (x == 'G') return(3)
  if (x == 'T') return(4)
}

```

```{r, dpi=300, fig.width=7, fig.height=4, fig.cap=fig.cap1}
dat <- subset(result$metrics$primer_sequencing_stats,
              data_source == data_source_name)
dat$match <- dat$from == dat$to
dat$match_count <- dat$match * dat$count

denominator_for_indels <- sum(dat$count) - sum(subset(dat, from == 'del', select = 'count', drop=T))
del_rate <- sum(subset(dat, from == 'del', select = 'count', drop=T))/denominator_for_indels
ins_rate <- sum(subset(dat, from == 'ins', select = 'count', drop=T))/denominator_for_indels
#1 - (n_deletions / denominator_for_indels)
#1 - (n_insertions / denominator_for_indels)

subs_dat <- subset(dat, 
                   from %in% c('A', 'C', 'G', 'T') &
                     to %in% c('A', 'C', 'G', 'T'))
subs_rate <- 1-(sum(subs_dat$match_count) / sum(subs_dat$count))

qual_subs <- subs_dat %>%
       group_by(match, qual) %>%
       summarize(numerator = sum(count))
qual_subs <- data.frame(qual_subs)
qual_totals <- subs_dat %>%
                 group_by(qual) %>%
                 summarize(denominator = sum(count))
qual_totals <- data.frame(qual_totals)
qual_subs <- merge(qual_subs, qual_totals, all.x = TRUE)

subs_by_qual <- 
subset(qual_subs, 
       match == TRUE, 
       select = c('qual', 'denominator', 'numerator'))
names(subs_by_qual) <- c('qual', 'total', 'matches')
mismatches_by_qual <- 
subset(qual_subs, 
       match == FALSE, 
       select = c('qual', 'numerator'))
names(mismatches_by_qual) <- c('qual', 'mismatches')
subs_by_qual <- merge(subs_by_qual, mismatches_by_qual, all.x = TRUE)
subs_by_qual$matches[is.na(subs_by_qual$matches)] <- 0
subs_by_qual$mismatches[is.na(subs_by_qual$mismatches)] <- 0
subs_by_qual <- subset(subs_by_qual, total > 1000)

subs_by_qual$num_qual <- sapply(subs_by_qual$qual, utf8ToInt) - 33
subs_by_qual$rate <- subs_by_qual$mismatches / subs_by_qual$total
subs_by_qual$SE <- sqrt(subs_by_qual$rate*(1-subs_by_qual$rate)/subs_by_qual$total)
subs_by_qual$E <- qnorm(.975)*subs_by_qual$SE
subs_by_qual$LB <- subs_by_qual$rate - subs_by_qual$E
subs_by_qual$UB <- subs_by_qual$rate + subs_by_qual$E



from_let <- 'A'
to_let <- 'A'
to_let <- 'T'
rate_mat <- matrix(rep(0, 4*4),ncol=4,nrow=4)
for (from_let in c('A', 'C', 'G', 'T')){
  for (to_let in c('A', 'C', 'G', 'T')){
    count <- sum(subset(dat, from == from_let & to == to_let, select='count', drop=T))
    total <- sum(subset(dat, from == from_let, select='count', drop=T))
    rate <- count / total
    rate_mat[let_to_int(from_let), let_to_int(to_let)] <- rate
  }
}
rate_mat <- data.frame(round(rate_mat, 5))
names(rate_mat) <- c('A', 'C', 'G', 'T')
row.names(rate_mat) <- c('A', 'C', 'G', 'T')



options(scipen=99)
p1 <- 
ggplot(subs_by_qual, aes(x=num_qual, y = rate)) +
  geom_point() +
  geom_errorbar(aes(ymax = UB, ymin = LB)) +
  ylab('Error Rate') +
  xlab('Quality Score')
```

**Substitution Rate: `r round(subs_rate,5)`**

**Deletion Rate: `r round(del_rate,5)`**

**Insertion Rate: `r round(ins_rate,5)`**


```{r, dpi=300, fig.width=7, fig.height=4, fig.cap=fig.cap1}
kable(rate_mat)
print(p1)
```

```{r, results='asis'}
cat('\n\n---\n\n')
```

