// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// gapQualityTweaker
Rcpp::NumericMatrix gapQualityTweaker(CharacterVector reads, NumericMatrix q_mat);
RcppExport SEXP MotifBinner2_gapQualityTweaker(SEXP readsSEXP, SEXP q_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type reads(readsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type q_mat(q_matSEXP);
    __result = Rcpp::wrap(gapQualityTweaker(reads, q_mat));
    return __result;
END_RCPP
}
// score_alignment_positions
Rcpp::List score_alignment_positions(CharacterVector reads, NumericMatrix q_mat);
RcppExport SEXP MotifBinner2_score_alignment_positions(SEXP readsSEXP, SEXP q_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type reads(readsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type q_mat(q_matSEXP);
    __result = Rcpp::wrap(score_alignment_positions(reads, q_mat));
    return __result;
END_RCPP
}
// trimFront_cpp
Rcpp::List trimFront_cpp(CharacterVector r_sread, CharacterVector r_qual, CharacterVector r_primer, std::vector<int> prefix_lens);
RcppExport SEXP MotifBinner2_trimFront_cpp(SEXP r_sreadSEXP, SEXP r_qualSEXP, SEXP r_primerSEXP, SEXP prefix_lensSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type r_sread(r_sreadSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type r_qual(r_qualSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type r_primer(r_primerSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type prefix_lens(prefix_lensSEXP);
    __result = Rcpp::wrap(trimFront_cpp(r_sread, r_qual, r_primer, prefix_lens));
    return __result;
END_RCPP
}
// transfer_gaps_cpp
Rcpp::List transfer_gaps_cpp(CharacterVector aligned_read, CharacterVector r_qual, NumericVector gap_only_cols);
RcppExport SEXP MotifBinner2_transfer_gaps_cpp(SEXP aligned_readSEXP, SEXP r_qualSEXP, SEXP gap_only_colsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type aligned_read(aligned_readSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type r_qual(r_qualSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gap_only_cols(gap_only_colsSEXP);
    __result = Rcpp::wrap(transfer_gaps_cpp(aligned_read, r_qual, gap_only_cols));
    return __result;
END_RCPP
}
// score_alignment_positions
Rcpp::List score_alignment_positions(CharacterVector reads, NumericMatrix q_mat);
RcppExport SEXP MotifBinner2_score_alignment_positions(SEXP readsSEXP, SEXP q_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type reads(readsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type q_mat(q_matSEXP);
    __result = Rcpp::wrap(score_alignment_positions(reads, q_mat));
    return __result;
END_RCPP
}
