# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

trimFront_cpp <- function(r_sread, r_qual, r_primer, prefix_lens) {
    .Call('MotifBinner2_trimFront_cpp', PACKAGE = 'MotifBinner2', r_sread, r_qual, r_primer, prefix_lens)
}

transfer_gaps_cpp <- function(aligned_read, r_qual, gap_only_cols) {
    .Call('MotifBinner2_transfer_gaps_cpp', PACKAGE = 'MotifBinner2', aligned_read, r_qual, gap_only_cols)
}

